apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: dag-video-
spec:
    entrypoint: dag
    arguments:
      parameters:
      - name: minio_url
      - name: minio_user
      - name: minio_pass
    templates:
    - name: python-script
      inputs:
        parameters:
        - name: image
        - name: minio_url
        - name: minio_user
        - name: minio_pass
        - name: data
      container:
          image: "{{inputs.parameters.image}}"
          command: [ python3 ]
          args: ["func.py", "{{inputs.parameters.data}}",
          "{{inputs.parameters.minio_url}}", "{{inputs.parameters.minio_user}}", "{{inputs.parameters.minio_pass}}"]
          resources:
                requests:
                        cpu: "1"
      activeDeadlineSeconds: "90"
      retryStrategy:
          limit: "5"
          retryPolicy: "Always"

    - name: dag
      inputs:
        parameters:
        - name: minio_url
        - name: minio_user
        - name: minio_pass
      dag:
          tasks:
          - name: split
            template: python-script
            arguments:
                parameters: [
                    {name: image, value: "chiuchienhao/vi-split2"},
                    {name: minio_url, value: "{{inputs.parameters.minio_url}}"},
                    {name: minio_user, value: "{{inputs.parameters.minio_user}}"},
                    {name: minio_pass, value: "{{inputs.parameters.minio_pass}}" },
                    {name: data, value: '{"src_name": "0", "DOP": "30", "detect_prob": 2}' }
                ]

          - name: extract
            dependencies: [split]
            template: python-script
            arguments:
                parameters: [
                    {name: image, value: "chiuchienhao/vi-extract2"},
                    {name: minio_url, value: "{{inputs.parameters.minio_url}}"},
                    {name: minio_user, value: "{{inputs.parameters.minio_user}}"},
                    {name: minio_pass, value: "{{inputs.parameters.minio_pass}}" },
                    {name: data, value: "{{item}}" }
                ]
            withParam: "{{tasks.split.outputs.result}}"
            
          - name: shuffle
            dependencies: [extract]
            template: python-script
            arguments:
                parameters: [
                    {name: image, value: "chiuchienhao/vi-shuffle2"},
                    {name: minio_url, value: "{{inputs.parameters.minio_url}}"},
                    {name: minio_user, value: "{{inputs.parameters.minio_user}}"},
                    {name: minio_pass, value: "{{inputs.parameters.minio_pass}}" },
                    {name: data, value: "{{tasks.extract.outputs.result}}" }
                ]
                
          - name: classify
            dependencies: [shuffle]
            template: python-script
            arguments:
                parameters: [
                    {name: image, value: "chiuchienhao/vi-classify2"},
                    {name: minio_url, value: "{{inputs.parameters.minio_url}}"},
                    {name: minio_user, value: "{{inputs.parameters.minio_user}}"},
                    {name: minio_pass, value: "{{inputs.parameters.minio_pass}}" },
                    {name: data, value: "{{item}}" }
                ]
            withParam: "{{tasks.shuffle.outputs.result}}"
