apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-5
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
